### ISSUE TITLE
node.js crash on Yosemite 10.10.1

### ISSUE THREAD

**Issue by nvrd** [TorrenTV/TorrenTV#70]
Running TorrenTV and either just pressing inside of the program or trying to add a torrent/magnet file results in the following error for me:

Uncaught node.js Error

TypeError: Cannot call method 'removeListener' of null
    at TLSSocket.onclose (/private/var/folders/cn/ljh9fkx118jc16s51xckzdqw0000gn/T/.org.chromium.Chromium.XsglRu/node_modules/chromecast-js/node_modules/castv2-client/node_modules/castv2/lib/client.js:53:13)
    at TLSSocket.g (events.js:187:16)
    at TLSSocket.EventEmitter.emit (events.js:98:17)
    at TCP.eval [as close] (net.js:459:12)

**Comment by Mel79** [comment]
This happens with me also in Mavericks 10.9.5.

**Comment by danielyc** [comment]
same node.js error on 10.10
Error: listen EADDRINUSE
    at exports._errnoException (util.js:677:11)
    at Server._listen2 (net.js:1080:14)
    at listen (net.js:1113:10)
    at Server.listen (net.js:1188:5)
    at xmlRokuServer (app://host/src/app/app.js:100:10)
    at eval (app://host/src/app/app.js:103:1)

**Comment by gallettigr** [comment]
Uncaught node.js Error

TypeError: Cannot read property 'documentElement' of undefined
    at Object.exports.parseStringSync (/Applications/TorrenTV.app/Contents/Resources/app.nw/node_modules/airplay-js/node_modules/plist-with-patches/lib/plist.js:79:10)
    at eval (/Applications/TorrenTV.app/Contents/Resources/app.nw/node_modules/airplay-js/airplay/client.js:184:25)
    at Socket.eval (/Applications/TorrenTV.app/Contents/Resources/app.nw/node_modules/airplay-js/airplay/client.js:39:13)
    at Socket.EventEmitter.emit (events.js:98:17)
    at readableAddChunk (_stream_readable.js:156:16)
    at Socket.Readable.push (_stream_readable.js:123:10)
    at TCP.onread (net.js:509:20)

**Comment by Ramon1981** [comment]
I had this too, somehow reinstalling the app fixed it... No idea why, but it did...
