### ISSUE TITLE
Error when starting 0.9.9 in Mac

### ISSUE THREAD

**Issue by BadChoice** [TorrenTV/TorrenTV#78]
TypeError: Cannot read property 'documentElement' of undefined
    at Object.exports.parseStringSync (/Applications/TorrenTV.app/Contents/Resources/app.nw/node_modules/airplay-js/node_modules/plist-with-patches/lib/plist.js:79:10)
    at eval (/Applications/TorrenTV.app/Contents/Resources/app.nw/node_modules/airplay-js/airplay/client.js:184:25)
    at Socket.eval (/Applications/TorrenTV.app/Contents/Resources/app.nw/node_modules/airplay-js/airplay/client.js:39:13)

**Comment by jorgealarconc** [comment]
same problem
