### ISSUE TITLE
Video file not playing

### ISSUE THREAD

**Issue by avmduck** [TorrenTV/TorrenTV#82]
A "Magnet" link and a "Torrent" file play fine. But, it will not work. When I try to play the exact same "Video" file.
      Any help would be "Greatly Appreciated!"

Windows 10
Roku 2 XD
TorrenTV  v.0.9.6

**Comment by n00bs** [comment]
Fixed

**Comment by blockridge1977** [comment]
I can't send files either. Running Roku 3... Streams torrents just fine, just not local file.

Am I doing something wrong?

**Comment by blockridge1977** [comment]
Oh and torrentv 9.6

**Comment by n00bs** [comment]
Download and replace the app.js (located in src/app) with my version of TorrenTV

**Comment by avmduck** [comment]
Thanx for trying n00bs..... Now i get an error:

Uncaught node.js Error

Error: Cannot find module 'subtitles-server'
    at Function.Module._resolveFilename (module.js:334:15)
    at Function.Module._load (module.js:273:25)
    at Module.require (module.js:360:17)
    at require (module.js:376:17)
    at window.require (eval at undefined, <anonymous>:1:112)
    at eval (app://host/src/app/app.js:8:29)

**Comment by blockridge1977** [comment]
Same here, same error.

**Comment by n00bs** [comment]
@avmduck  @blockridge1977  
Just fixed the error with my new version of app.js. Just replace it with the existing version and it should now work!

**Comment by avmduck** [comment]
Thanx n00bs
Worked Great!

**Comment by blockridge1977** [comment]
I'll try tonight. Thanks for the work n00bs!
