### ISSUE TITLE
Uncaught node.js Error

### ISSUE THREAD

**Issue by kirius20** [TorrenTV/TorrenTV#93]
Hi.
When I start the application I get the following error:

"Uncaught node.js Error TypeError: Cannot read property 'documentElement' of undefined at Object.exports.parseStringSync (/private/var/folders/9d/r2_xmrqx049chwggq7cm52pr0000gn/T/.org.chromium.Chromium.UKI0Lp/node_modules/airplay-js/node_modules/plist-with-patches/lib/plist.js:79:10) at eval (/private/var/folders/9d/r2_xmrqx049chwggq7cm52pr0000gn/T/.org.chromium.Chromium.UKI0Lp/node_modules/airplay-js/airplay/client.js:184:25) at Socket.eval (/private/var/folders/9d/r2_xmrqx049chwggq7cm52pr0000gn/T/.org.chromium.Chromium.UKI0Lp/node_modules/airplay-js/airplay/client.js:39:13)"

I have OS X 10.11.1

**Comment by wearelogik** [comment]
Get the same error, it only occurs with torrent files tho. Use magnets instead and it works just fine.

**Comment by kirius20** [comment]
I have not gotten to use any type of file. The error occurs when the program starts me if I have the AirPlay enabled

**Comment by mmarquez661** [comment]
I am having the same issue :(

**Comment by diogoviannaaraujo** [comment]
+1

**Comment by aghuwalewala** [comment]
Me too.

**Comment by lesha888** [comment]
+1

**Comment by aullman** [comment]
+1

**Comment by aullman** [comment]
I was using v0.9.6 and I just updated to v0.9.9 and I still have the same issue. I'm using OSX Yosemite 10.10.5.

```
Uncaught node.js Error

TypeError: Cannot read property 'documentElement' of undefined
    at Object.exports.parseStringSync (/Applications/TorrenTV.app/Contents/Resources/app.nw/node_modules/airplay-js/node_modules/plist-with-patches/lib/plist.js:79:10)
    at eval (/Applications/TorrenTV.app/Contents/Resources/app.nw/node_modules/airplay-js/airplay/client.js:184:25)
    at Socket.eval (/Applications/TorrenTV.app/Contents/Resources/app.nw/node_modules/airplay-js/airplay/client.js:39:13)
    at Socket.EventEmitter.emit (events.js:98:17)
    at readableAddChunk (_stream_readable.js:156:16)
    at Socket.Readable.push (_stream_readable.js:123:10)
    at TCP.onread (net.js:509:20)
```

**Comment by codygman** [comment]
Shot in the dark, but this function looks easy to break and is related if
you trace the callstack:
https://github.com/guerrerocarlos/node-airplay-js/blob/master/airplay/client.js#L94

**Comment by wearelogik** [comment]
TorrenTV is dead. Just use http://powder.media/

**Comment by kirius20** [comment]
Now I use Stremio. It is the best app

**Comment by wearelogik** [comment]
Thank you @kirius20

I was a bit hasty when i posted my recommendation, it's been a while and i completely forgot that the key benefit of this app was streaming to Apple TV. Something Powder Player doesn't let you do. Tho, for use on the computer, Powder is excellent.

Checking out Streaming! Thanks for the tip.

**Comment by semikolon** [comment]
Stremio didn't work for me. Login doesn't even work. and it looks kinda shady and some people were reporting trojans in the installer... so...

**Comment by semikolon** [comment]
So, get this same error still, with airplay-js, even with magnet links

**Comment by okibcn** [comment]
I am having the same issue. I am using it in a Windows 10 Aniversary Update, Latest Java:
```
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) Client VM (build 25.101-b13, mixed mode, sharing)
```

Just after installing the windows installer and after running it I got:

```
Uncaught node.js Error

TypeError: Cannot read property 'documentElement' of undefined
    at Object.exports.parseStringSync (C:\Users\Me\AppData\Local\TorrenTV\node_modules\airplay-js\node_modules\plist-with-patches\lib\plist.js:79:10)
    at eval (C:\Users\Me\AppData\Local\TorrenTV\node_modules\airplay-js\airplay\client.js:184:25)
    at Socket.eval (C:\Users\Me\AppData\Local\TorrenTV\node_modules\airplay-js\airplay\client.js:39:13)
    at Socket.EventEmitter.emit (events.js:98:17)
    at readableAddChunk (_stream_readable.js:156:16)
    at Socket.Readable.push (_stream_readable.js:123:10)
    at TCP.onread (net.js:509:20)
```
Obviously it doesn't leave me test any torrent file, magnet or video file. Any clue? I can provide more feedback if needed.

Thanks

**Comment by luisbuchelli** [comment]
+1 same issue

**Comment by GETandSELECT** [comment]
+1 same issue on latest macOS Sierra and tvOS

this the error on AppleTV
![img_0354](https://cloud.githubusercontent.com/assets/10598483/24585625/acad9cba-178f-11e7-9f9a-b69af14728ee.JPG)
